# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import card_generation_pb2 as grpc_dot_card__generation__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc/card_generation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CardGenerationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCards = channel.stream_stream(
                '/sigmacards.cards.v1.CardGenerationService/GenerateCards',
                request_serializer=grpc_dot_card__generation__pb2.GenerateCardsStreamRequest.SerializeToString,
                response_deserializer=grpc_dot_card__generation__pb2.GenerateCardsStreamResponse.FromString,
                _registered_method=True)


class CardGenerationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCards(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardGenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCards': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateCards,
                    request_deserializer=grpc_dot_card__generation__pb2.GenerateCardsStreamRequest.FromString,
                    response_serializer=grpc_dot_card__generation__pb2.GenerateCardsStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sigmacards.cards.v1.CardGenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sigmacards.cards.v1.CardGenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardGenerationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCards(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sigmacards.cards.v1.CardGenerationService/GenerateCards',
            grpc_dot_card__generation__pb2.GenerateCardsStreamRequest.SerializeToString,
            grpc_dot_card__generation__pb2.GenerateCardsStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
