#!/usr/bin/env python3
# GENERATED BY CHATGPT (CODEX)
from __future__ import annotations

import argparse
import json
import random
import sys
import time
from dataclasses import dataclass
from typing import Any
from uuid import uuid4

import requests


@dataclass
class ApiClient:
    base_url: str
    session: requests.Session

    def _url(self, path: str) -> str:
        return f"{self.base_url.rstrip('/')}{path}"

    def _raise_for_status(self, response: requests.Response, action: str) -> None:
        if response.ok:
            return
        try:
            payload = response.json()
        except ValueError:
            payload = response.text
        raise RuntimeError(f"{action} failed: {response.status_code} {payload}")

    def register(self, username: str, email: str, password: str) -> dict[str, Any]:
        response = self.session.post(
            self._url("/api/v1/auth/register"),
            json={"username": username, "email": email, "password": password},
            timeout=30,
        )
        self._raise_for_status(response, "register")
        return response.json()

    def login(self, email: str, password: str) -> dict[str, Any]:
        response = self.session.post(
            self._url("/api/v1/auth/login"),
            json={"email": email, "password": password},
            timeout=30,
        )
        self._raise_for_status(response, "login")
        return response.json()

    def create_deck(self, title: str, description: str) -> dict[str, Any]:
        response = self.session.post(
            self._url("/api/v1/decks/"),
            json={"title": title, "description": description},
            timeout=30,
        )
        self._raise_for_status(response, "create deck")
        return response.json()

    def create_card(self, deck_id: str, front: str, back: str, position: int) -> dict[str, Any]:
        response = self.session.post(
            self._url(f"/api/v1/cards/decks/{deck_id}/cards"),
            json={
                "card_type": "key_terms",
                "position": position,
                "content": {"front": front, "back": back},
            },
            timeout=30,
        )
        self._raise_for_status(response, "create card")
        return response.json()

    def get_due_cards(self, deck_id: str, limit: int = 20) -> list[dict[str, Any]]:
        response = self.session.get(
            self._url("/api/v1/review/due"),
            params={"deck_id": deck_id, "limit": limit},
            timeout=30,
        )
        self._raise_for_status(response, "get due cards")
        return response.json()

    def submit_review(self, user_card_id: str, rating: int, version: int, duration_ms: int) -> dict[str, Any]:
        response = self.session.post(
            self._url(f"/api/v1/review/{user_card_id}"),
            json={"rating": rating, "duration_ms": duration_ms, "version": version},
            timeout=30,
        )
        self._raise_for_status(response, "submit review")
        return response.json()


def build_demo_cards() -> list[tuple[str, str]]:
    return [
        ("HTTP status 200", "OK"),
        ("Python GIL", "Global Interpreter Lock"),
        ("PostgreSQL JSONB", "Binary JSON storage type"),
        ("FSRS", "Free Spaced Repetition Scheduler"),
    ]


def choose_rating(index: int, cycle: int) -> int:
    pattern = [3, 4, 2, 3]
    return pattern[(index + cycle) % len(pattern)]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Register a user and simulate a small study flow through the SigmaCards API.")
    parser.add_argument("--base-url", default="http://localhost:8010", help="API base URL, e.g. http://localhost:8000")
    parser.add_argument("--password", default="SigmaCards123!", help="Password for the generated demo user")
    parser.add_argument("--rounds", type=int, default=2, help="How many review rounds to simulate")
    parser.add_argument("--sleep-seconds", type=float, default=0.0, help="Optional delay between rounds")
    parser.add_argument("--session-file", default=None, help="Optional path to save generated credentials/deck metadata as JSON")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    run_id = uuid4().hex[:8]
    username = f"demo_{run_id}"
    email = f"{username}@example.com"
    password = args.password
    session_file = args.session_file or f"demo-study-session-{run_id}.json"

    session = requests.Session()
    client = ApiClient(base_url=args.base_url, session=session)

    print(f"[1/6] Registering user {email}")
    register_tokens = client.register(username=username, email=email, password=password)
    print("     Registration successful")

    print(f"[2/6] Logging in as {email}")
    login_tokens = client.login(email=email, password=password)
    session.headers.update({"Authorization": f"Bearer {login_tokens['access_token']}"})
    print("     Login successful")

    print("[3/6] Creating demo deck")
    deck = client.create_deck(
        title=f"Demo deck {run_id}",
        description="Deck created by scripts/simulate_learning_flow.py",
    )
    deck_id = deck["id"]
    print(f"     Deck created: {deck_id}")

    print("[4/6] Creating demo cards")
    created_cards: list[dict[str, Any]] = []
    for position, (front, back) in enumerate(build_demo_cards()):
        card = client.create_card(deck_id=deck_id, front=front, back=back, position=position)
        created_cards.append(card)
        print(f"     Card {position + 1}: {card['id']} | {front} -> {back}")

    print("[5/6] Simulating study rounds")
    random.seed(42)
    reviews_submitted = 0
    for cycle in range(args.rounds):
        due_cards = client.get_due_cards(deck_id=deck_id, limit=20)
        if not due_cards:
            print(f"     Round {cycle + 1}: no due cards, stopping early")
            break

        print(f"     Round {cycle + 1}: {len(due_cards)} due cards")
        for index, due_card in enumerate(due_cards):
            rating = choose_rating(index=index, cycle=cycle)
            duration_ms = random.randint(1200, 4500)
            review = client.submit_review(
                user_card_id=due_card["user_card_id"],
                rating=rating,
                version=due_card["version"],
                duration_ms=duration_ms,
            )
            reviews_submitted += 1
            front = due_card["content"].get("front", "<no front>")
            print(
                f"       - {front!r}: rating={rating}, duration_ms={duration_ms}, "
                f"next_due={review['next_due']}, new_state={review['new_state']}"
            )

        if args.sleep_seconds > 0 and cycle < args.rounds - 1:
            time.sleep(args.sleep_seconds)

    session_payload = {
        "base_url": args.base_url.rstrip("/"),
        "email": email,
        "password": password,
        "deck_id": deck_id,
        "cards_created": len(created_cards),
        "reviews_submitted": reviews_submitted,
    }
    with open(session_file, "w", encoding="utf-8") as fh:
        json.dump(session_payload, fh, ensure_ascii=False, indent=2)

    login_curl = (
        f"curl -X POST {args.base_url.rstrip('/')}"
        "/api/v1/auth/login -H 'Content-Type: application/json' "
        f"-d '{{\"email\":\"{email}\",\"password\":\"{password}\"}}'"
    )
    due_cards_curl = (
        f"curl '{args.base_url.rstrip('/')}"
        f"/api/v1/review/due?deck_id={deck_id}&limit=20' "
        "-H 'Authorization: Bearer <token>'"
    )

    print("[6/6] Done")
    print("     Summary:")
    print(f"       user: {email}")
    print(f"       password: {password}")
    print(f"       register token type: {register_tokens['token_type']}")
    print(f"       deck: {deck_id}")
    print(f"       cards created: {len(created_cards)}")
    print(f"       reviews submitted: {reviews_submitted}")
    print(f"       session file: {session_file}")
    print("     How to continue with the same account:")
    print(f"       1. Login again: {login_curl}")
    print("       2. Use the returned access_token in Authorization: Bearer <token>")
    print(f"       3. Request due cards: {due_cards_curl}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("Interrupted by user", file=sys.stderr)
        raise SystemExit(130)