# GENERATED BY CHAT GPT (CODEX)
import json
import os
import sys
import types
import unittest
from unittest.mock import patch

os.environ.setdefault("DATABASE_URL", "sqlite://")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")
os.environ.setdefault("SECRET_KEY", "test-secret")
os.environ.setdefault("ACCESS_TOKEN_EXPIRE_MINUTES", "30")
os.environ.setdefault("REFRESH_TOKEN_EXPIRE_DAYS", "7")

redis_module = types.ModuleType("redis")


class _RedisStub:
    @classmethod
    def from_url(cls, *args, **kwargs):
        raise AssertionError("Redis.from_url should be patched in tests")


redis_module.Redis = _RedisStub
sys.modules.setdefault("redis", redis_module)

from fastapi import HTTPException
from pydantic import BaseModel

from src.services.idempotency_service import IdempotencyService


class DummyResponse(BaseModel):
    value: int


class FakeRedis:
    def __init__(self):
        self.storage = {}

    def get(self, key):
        return self.storage.get(key)

    def set(self, key, value, nx=False, ex=None):
        if nx and key in self.storage:
            return False
        self.storage[key] = value
        return True

    def eval(self, script, keys_count, lock_key, lock_token):
        if self.storage.get(lock_key) == lock_token:
            self.storage.pop(lock_key, None)
            return 1
        return 0


class IdempotencyServiceTests(unittest.TestCase):
    def test_returns_cached_response_for_duplicate_request(self):
        fake_redis = FakeRedis()
        calls = {"count": 0}

        def operation():
            calls["count"] += 1
            return DummyResponse(value=42)

        with patch("src.services.idempotency_service.get_redis", return_value=fake_redis):
            first_result = IdempotencyService.execute(
                namespace="review-card:123",
                idempotency_key="same-key",
                user_id="user-1",
                payload={"rating": 4, "version": 1},
                operation=operation,
                response_model=DummyResponse,
            )
            second_result = IdempotencyService.execute(
                namespace="review-card:123",
                idempotency_key="same-key",
                user_id="user-1",
                payload={"rating": 4, "version": 1},
                operation=operation,
                response_model=DummyResponse,
            )

        self.assertEqual(calls["count"], 1)
        self.assertEqual(first_result.value, 42)
        self.assertEqual(second_result.value, 42)

    def test_rejects_same_key_with_different_payload(self):
        fake_redis = FakeRedis()
        fingerprint = IdempotencyService.build_fingerprint(
            namespace="create-card:456",
            user_id="user-1",
            payload={"content": {"front": "A"}},
        )
        response_key = IdempotencyService._response_key("create-card:456", "same-key")
        fake_redis.storage[response_key] = json.dumps(
            {
                "fingerprint": fingerprint,
                "response": {"value": 7},
            }
        )

        with patch("src.services.idempotency_service.get_redis", return_value=fake_redis):
            with self.assertRaises(HTTPException) as ctx:
                IdempotencyService.execute(
                    namespace="create-card:456",
                    idempotency_key="same-key",
                    user_id="user-1",
                    payload={"content": {"front": "B"}},
                    operation=lambda: DummyResponse(value=9),
                    response_model=DummyResponse,
                )

        self.assertEqual(ctx.exception.status_code, 409)


if __name__ == "__main__":
    unittest.main()