#!/usr/bin/env python3
# GENERATED BY CHAT GPT URA URA URA
"""Demo e2e script:
1) register
2) login
3) create deck
4) upload 3 images via presigned POST
5) create card that references uploaded images
6) fetch created card
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import pathlib
import uuid
from typing import Any

import requests


DEFAULT_BASE_URL = "http://localhost:8010/api/v1"


def _json_or_raise(resp: requests.Response) -> dict[str, Any]:
    try:
        data = resp.json()
    except Exception:
        resp.raise_for_status()
        raise RuntimeError("Response is not JSON")
    if resp.status_code >= 400:
        raise RuntimeError(f"HTTP {resp.status_code}: {data}")
    return data


def register(base_url: str, username: str, email: str, password: str) -> dict[str, Any]:
    payload = {"username": username, "email": email, "password": password}
    resp = requests.post(f"{base_url}/auth/register", json=payload, timeout=30)
    if resp.status_code == 409:
        return login(base_url, email, password)
    return _json_or_raise(resp)


def login(base_url: str, email: str, password: str) -> dict[str, Any]:
    payload = {"email": email, "password": password}
    resp = requests.post(f"{base_url}/auth/login", json=payload, timeout=30)
    return _json_or_raise(resp)


def auth_headers(access_token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {access_token}"}


def create_deck(base_url: str, token: str, title: str) -> dict[str, Any]:
    payload = {"title": title, "description": "Deck created by demo script"}
    resp = requests.post(
        f"{base_url}/decks/",
        json=payload,
        headers=auth_headers(token),
        timeout=30,
    )
    return _json_or_raise(resp)


def request_image_upload(base_url: str, token: str, content_type: str) -> dict[str, Any]:
    payload = {"content_type": content_type}
    resp = requests.post(
        f"{base_url}/images/",
        json=payload,
        headers=auth_headers(token),
        timeout=30,
    )
    return _json_or_raise(resp)


def upload_file_to_storage(upload_info: dict[str, Any], image_path: pathlib.Path, content_type: str) -> None:
    upload_url = upload_info["upload_url"]
    upload_fields = upload_info.get("upload_fields") or {}

    with image_path.open("rb") as file_obj:
        files = {"file": (image_path.name, file_obj, content_type)}
        resp = requests.post(upload_url, data=upload_fields, files=files, timeout=60)
        if resp.status_code >= 400:
            raise RuntimeError(
                f"Storage upload failed for {image_path}: HTTP {resp.status_code}, body={resp.text[:300]}"
            )


def create_card_with_images(
    base_url: str,
    token: str,
    deck_id: str,
    image_ids: list[str],
) -> dict[str, Any]:
    front_blocks = [{"id": "front-text", "type": "text", "content": "Назови объекты на картинках"}]
    back_blocks = []

    for index, image_id in enumerate(image_ids, start=1):
        block_id = f"img-{index}"
        front_blocks.append({"id": block_id, "type": "image", "image_id": image_id})
        back_blocks.append({"id": f"caption-{index}", "type": "text", "content": f"Картинка #{index}"})

    payload = {
        "content": {
            "front": front_blocks,
            "back": back_blocks,
        },
        "position": 0,
    }

    resp = requests.post(
        f"{base_url}/cards/decks/{deck_id}/cards",
        json=payload,
        headers=auth_headers(token),
        timeout=30,
    )
    return _json_or_raise(resp)


def get_card(base_url: str, token: str, card_id: str) -> dict[str, Any]:
    resp = requests.get(
        f"{base_url}/cards/{card_id}",
        headers=auth_headers(token),
        timeout=30,
    )
    return _json_or_raise(resp)


def update_card_remove_last_image(
    base_url: str,
    token: str,
    card_id: str,
    version: int,
    image_ids: list[str],
) -> dict[str, Any]:
    kept_image_ids = image_ids[:-1]

    front_blocks = [{"id": "front-text", "type": "text", "content": "Назови объекты на картинках (updated)"}]
    back_blocks = []
    for index, image_id in enumerate(kept_image_ids, start=1):
        front_blocks.append({"id": f"img-{index}", "type": "image", "image_id": image_id})
        back_blocks.append({"id": f"caption-{index}", "type": "text", "content": f"Картинка #{index}"})

    payload = {
        "version": version,
        "content": {
            "front": front_blocks,
            "back": back_blocks,
        },
    }

    resp = requests.put(
        f"{base_url}/cards/{card_id}",
        json=payload,
        headers=auth_headers(token),
        timeout=30,
    )
    return _json_or_raise(resp)


def detect_content_type(path: pathlib.Path) -> str:
    guessed, _ = mimetypes.guess_type(str(path))
    if guessed in {"image/png", "image/jpeg", "image/webp"}:
        return guessed
    raise RuntimeError(
        f"Unsupported file type for {path}. Use PNG/JPEG/WEBP or pass files with proper extension."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run full image-card flow against SigmaCards API")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="API base URL")
    parser.add_argument(
        "--images",
        nargs=3,
        default=["tests/image1.jpg", "tests/image2.jpg", "tests/image3.png"],
        metavar=("IMG1", "IMG2", "IMG3"),
        help="Three local image files",
    )
    parser.add_argument("--email", default=None, help="User email (auto-generated if omitted)")
    parser.add_argument("--password", default="TestPassword123!", help="User password")
    parser.add_argument("--username", default=None, help="Username (auto-generated if omitted)")
    args = parser.parse_args()

    run_id = uuid.uuid4().hex[:8]
    username = args.username or f"img-demo-{run_id}"
    email = args.email or f"img-demo-{run_id}@example.com"

    image_paths = [pathlib.Path(p).expanduser().resolve() for p in args.images]
    for image_path in image_paths:
        if not image_path.exists():
            raise RuntimeError(f"Image file not found: {image_path}")

    tokens = register(args.base_url, username, email, args.password)
    access_token = tokens["access_token"]
    print(f"[1/8] Auth ok. user={email}")

    deck = create_deck(args.base_url, access_token, title=f"Demo deck {run_id}")
    deck_id = deck["id"]
    print(f"[2/8] Deck created: {deck_id}")

    image_ids: list[str] = []
    for idx, image_path in enumerate(image_paths, start=1):
        content_type = detect_content_type(image_path)
        upload_info = request_image_upload(args.base_url, access_token, content_type)
        upload_file_to_storage(upload_info, image_path, content_type)
        image_id = str(upload_info["image_id"])
        image_ids.append(image_id)
        print(f"[3.{idx}/8] Image uploaded: {image_path.name} -> image_id={image_id}")

    card = create_card_with_images(args.base_url, access_token, deck_id, image_ids)
    card_id = card["id"]
    print(f"[4/8] Card created: {card_id}")

    fetched_card = get_card(args.base_url, access_token, card_id)
    print("[5/8] Card fetched")

    print("\n=== CARD RESPONSE ===")
    print(json.dumps(fetched_card, ensure_ascii=False, indent=2))

    updated_card = update_card_remove_last_image(
        args.base_url,
        access_token,
        card_id,
        int(fetched_card["version"]),
        image_ids,
    )
    print("[6/8] Card updated (one image removed)")
    print("\n=== UPDATED CARD RESPONSE ===")
    print(json.dumps(updated_card, ensure_ascii=False, indent=2))

    reread_card = get_card(args.base_url, access_token, card_id)
    print("[7/8] Card re-fetched after update")
    print("\n=== RE-READ CARD RESPONSE ===")
    print(json.dumps(reread_card, ensure_ascii=False, indent=2))
    print("[8/8] Done")


if __name__ == "__main__":
    main()