"""optimistic locking

Revision ID: 104f66bffd70
Revises: 20871bc0aabe
Create Date: 2026-02-27 20:46:41.579221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104f66bffd70'
down_revision: Union[str, Sequence[str], None] = '20871bc0aabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('flashcards', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('user_cards', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cards', 'version')
    op.drop_column('flashcards', 'version')
    op.drop_column('decks', 'version')
    # ### end Alembic commands ###
