"""flashcard model changes

Revision ID: 1ae24c3d7f93
Revises: f380bb567409
Create Date: 2026-03-24 11:38:39.415541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae24c3d7f93'
down_revision: Union[str, Sequence[str], None] = 'f380bb567409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'card_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
