"""Initial migration

Revision ID: 20871bc0aabe
Revises: c2b1071db825
Create Date: 2025-12-05 12:41:51.247645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20871bc0aabe'
down_revision: Union[str, Sequence[str], None] = 'c2b1071db825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fsrs_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_deck_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_refresh_token'), 'refresh_sessions', ['refresh_token'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_user_id'), 'sources', ['user_id'], unique=False)
    op.create_table('deck_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_subscriptions_deck_id'), 'deck_subscriptions', ['deck_id'], unique=False)
    op.create_index('ix_deck_subscriptions_user_deck', 'deck_subscriptions', ['user_id', 'deck_id'], unique=True)
    op.create_index(op.f('ix_deck_subscriptions_user_id'), 'deck_subscriptions', ['user_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    op.create_table('user_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cards_card_id'), 'user_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_cards_due'), 'user_cards', ['due'], unique=False)
    op.create_index(op.f('ix_user_cards_user_id'), 'user_cards', ['user_id'], unique=False)
    op.create_table('card_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_card_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_actions_user_card_id'), 'card_actions', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_card_actions_user_id'), 'card_actions', ['user_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_card_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('state_before', sa.Integer(), nullable=False),
    sa.Column('due_after', sa.DateTime(), nullable=False),
    sa.Column('stability_after', sa.Float(), nullable=False),
    sa.Column('difficulty_after', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('review_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_review_datetime'), 'review_logs', ['review_datetime'], unique=False)
    op.create_index(op.f('ix_review_logs_user_card_id'), 'review_logs', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_user_card_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_review_datetime'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_card_actions_user_id'), table_name='card_actions')
    op.drop_index(op.f('ix_card_actions_user_card_id'), table_name='card_actions')
    op.drop_table('card_actions')
    op.drop_index(op.f('ix_user_cards_user_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_due'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_card_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_deck_subscriptions_user_id'), table_name='deck_subscriptions')
    op.drop_index('ix_deck_subscriptions_user_deck', table_name='deck_subscriptions')
    op.drop_index(op.f('ix_deck_subscriptions_deck_id'), table_name='deck_subscriptions')
    op.drop_table('deck_subscriptions')
    op.drop_index(op.f('ix_sources_user_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_refresh_sessions_refresh_token'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_table('users')
    # ### end Alembic commands ###
