"""images support

Revision ID: f380bb567409
Revises: f6831d8687e5
Create Date: 2026-03-24 10:58:14.784787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f380bb567409'
down_revision: Union[str, Sequence[str], None] = 'f6831d8687e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_name')
    )
    op.create_table('card_images',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'image_id')
    )
    op.drop_index('ix_card_actions_user_card_id', table_name='card_actions')
    op.drop_index('ix_card_actions_user_id', table_name='card_actions')
    op.drop_table('card_actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_actions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], name='card_actions_user_card_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='card_actions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='card_actions_pkey')
    )
    op.create_index('ix_card_actions_user_id', 'card_actions', ['user_id'], unique=False)
    op.create_index('ix_card_actions_user_card_id', 'card_actions', ['user_card_id'], unique=False)
    op.drop_table('card_images')
    op.drop_table('images')
    # ### end Alembic commands ###
