"""fsrs changes

Revision ID: f6831d8687e5
Revises: 104f66bffd70
Create Date: 2026-03-20 21:16:01.587879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6831d8687e5'
down_revision: Union[str, Sequence[str], None] = '104f66bffd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # manually changed
    op.add_column('user_cards', sa.Column('step', sa.Integer(), nullable=True))
    op.execute("UPDATE user_cards SET state = 1 WHERE state = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # manually changed
    op.execute("UPDATE user_cards SET state = 0 WHERE state = 1 AND step IS NULL AND stability = 0 AND difficulty = 0")
    op.drop_column('user_cards', 'step')
    # ### end Alembic commands ###
